;;; ==========================================================================
;;; Db_Presets.lsp - Master Workspace & Industry Drafting Profiles Dictionary
;;; Part of Cad-Setup-v3 Horizontal Layered Architecture
;;; Layer: Database (Level 2 - Pure Data)
;;; ==========================================================================

;; ===========================================================================
;; MASTER PRESET SPECIFICATIONS
;; Each entry maps a Preset Code to its title, description, and list of
;; control key-value pairs for the settings configurator dialog.
;; ===========================================================================

(setq *CadSetup-Presets-Data*
  '(
    ;; 1. Architectural (Metric Millimeters / ISO)
    ("ARCH_MM"
     (:label . "Architectural (mm)")
     (:status . "Applied Preset: Architectural Metric ISO (Millimeters, LUPREC=0, INSUNITS=mm, Ortho ON)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "0")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "2")
       ("pop_insunits". "4")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "5")   ("sld_pb"  . "5")
       ("eb_grp"      . "6")   ("sld_grp" . "6")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "1")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "1")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 2. Architectural Masterplan & Site Planning (Metric Meters)
    ("ARCH_M"
     (:label . "Arch Masterplan (m)")
     (:status . "Applied Preset: Architectural Masterplan (Meters, LUPREC=3, INSUNITS=Meters, Ortho ON)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "3")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "2")
       ("pop_insunits". "6")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "6")   ("sld_pb"  . "6")
       ("eb_grp"      . "7")   ("sld_grp" . "7")
       ("eb_ap"       . "12")  ("sld_ap"  . "12")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "1")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "1")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 3. Architectural (Imperial Feet & Fractional Inches)
    ("ARCH"
     (:label . "Architectural (ft-in)")
     (:status . "Applied Preset: Architectural Imperial (Feet & 1/16\" Inches, INSUNITS=Inches, Ortho ON)")
     (:tiles . (
       ("pop_lunits"  . "3")
       ("pop_luprec"  . "4")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "2")
       ("pop_insunits". "1")
       ("pop_meas"    . "0")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "5")   ("sld_pb"  . "5")
       ("eb_grp"      . "6")   ("sld_grp" . "6")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "1")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "1")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 4. Structural Engineering (Metric Millimeters)
    ("STRUCT_MM"
     (:label . "Structural (mm)")
     (:status . "Applied Preset: Structural Engineering (Metric mm, Precision 0.0, Lineweights ON)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "1")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "2")
       ("pop_insunits". "4")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "6")   ("sld_pb"  . "6")
       ("eb_grp"      . "7")   ("sld_grp" . "7")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "1")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "1")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 5. Mechanical / Manufacturing (Metric Millimeters)
    ("MECH_MM"
     (:label . "Mechanical (mm)")
     (:status . "Applied Preset: Mechanical / Manufacturing (Metric mm, Precision 0.00, Tangent/Quad Snaps ON)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "2")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "2")
       ("pop_insunits". "4")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "8")   ("sld_cur" . "8")
       ("eb_pb"       . "4")   ("sld_pb"  . "4")
       ("eb_grp"      . "5")   ("sld_grp" . "5")
       ("eb_ap"       . "8")   ("sld_ap"  . "8")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "2")
       ("tog_grid"    . "1")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "0")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 6. Civil Engineering & Surveying (Metric Meters)
    ("CIVIL_M"
     (:label . "Civil / Survey (m)")
     (:status . "Applied Preset: Civil / Surveying (Meters 0.000, DMS Angles, North Azimuth, Node Snaps)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "3")
       ("pop_aunits"  . "1")
       ("pop_auprec"  . "2")
       ("pop_insunits". "6")
       ("pop_meas"    . "1")
       ("pop_angd"    . "1")
       ("pop_angb"    . "1")
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "5")   ("sld_pb"  . "5")
       ("eb_grp"      . "6")   ("sld_grp" . "6")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "3")
       ("tog_grid"    . "1")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "0")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 7. Electrical & MEP Schematics
    ("ELEC_MEP"
     (:label . "Electrical / MEP")
     (:status . "Applied Preset: Electrical & MEP Schematics (Snap/Grid Aligned, Ortho ON, MIRRTEXT=0)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "0")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "0")
       ("pop_insunits". "4")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "50")  ("sld_cur" . "50")
       ("eb_pb"       . "5")   ("sld_pb"  . "5")
       ("eb_grp"      . "6")   ("sld_grp" . "6")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "1")
       ("tog_snap"    . "1")
       ("tog_ortho"   . "1")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 8. Isometric 2.5D Drafting
    ("ISO_25D"
     (:label . "Isometric 2.5D")
     (:status . "Applied Preset: Isometric 2.5D Drafting (SNAPSTYLE=Isometric, Ortho ON, Grid ON, 100% Crosshair)")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "1")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "2")
       ("pop_insunits". "4")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "5")   ("sld_pb"  . "5")
       ("eb_grp"      . "6")   ("sld_grp" . "6")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "1")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "1")
       ("tog_snap"    . "1")
       ("tog_ortho"   . "1")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 9. Full Screen Pro Drafter
    ("FULL_CROSS"
     (:label . "100% Pro Drafter")
     (:status . "Applied Preset: 100% Pro Drafter & 4K High Visibility Ergonomics")
     (:tiles . (
       ("eb_cur"      . "100") ("sld_cur" . "100")
       ("eb_pb"       . "7")   ("sld_pb"  . "7")
       ("eb_grp"      . "8")   ("sld_grp" . "8")
       ("eb_ap"       . "14")  ("sld_ap"  . "14")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_lw"      . "1")
       ("tog_grid"    . "1")
     )))

    ;; 10. Presentation & Plot Preparation
    ("PRESENT_PLOT"
     (:label . "Plot / Present")
     (:status . "Applied Preset: Presentation & Plot Preparation (Lineweights ON, Grid OFF, Snaps OFF)")
     (:tiles . (
       ("eb_cur"      . "5")   ("sld_cur" . "5")
       ("eb_pb"       . "3")   ("sld_pb"  . "3")
       ("eb_grp"      . "4")   ("sld_grp" . "4")
       ("eb_ap"       . "8")   ("sld_ap"  . "8")
       ("pop_dyn"     . "0")
       ("pop_sp"      . "0")
       ("pop_drag"    . "2")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "0")
       ("tog_grid"    . "0")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "0")
       ("tog_lw"      . "1")
       ("tog_mirr"    . "0")
     )))

    ;; 11. AutoCAD Factory Defaults
    ("DEFAULT"
     (:label . "Factory Default")
     (:status . "Reset to Standard Factory Default CAD Settings")
     (:tiles . (
       ("pop_lunits"  . "1")
       ("pop_luprec"  . "4")
       ("pop_aunits"  . "0")
       ("pop_auprec"  . "0")
       ("pop_insunits". "4")
       ("pop_meas"    . "1")
       ("pop_angd"    . "0")
       ("pop_angb"    . "0")
       ("eb_cur"      . "5")   ("sld_cur" . "5")
       ("eb_pb"       . "3")   ("sld_pb"  . "3")
       ("eb_grp"      . "5")   ("sld_grp" . "5")
       ("eb_ap"       . "10")  ("sld_ap"  . "10")
       ("pop_dyn"     . "3")
       ("pop_sp"      . "3")
       ("pop_drag"    . "2")
       ("pop_snst"    . "0")
       ("pop_selopt"  . "1")
       ("pop_osm"     . "1")
       ("tog_grid"    . "0")
       ("tog_snap"    . "0")
       ("tog_ortho"   . "0")
       ("tog_lw"      . "0")
       ("tog_mirr"    . "0")
     )))
  )
)

;; ===========================================================================
;; DATABASE ACCESSORS
;; ===========================================================================

;; CadSetup:GetPresetData - Retrieves preset specification record by key
(defun CadSetup:GetPresetData (presetKey / match)
  (if (and presetKey (= (type presetKey) 'STR))
    (assoc (strcase presetKey) *CadSetup-Presets-Data*)
    nil
  )
)

(princ "\n[Database/Db_Presets.lsp] Workspace & Industry Presets loaded.")
(princ)
